services:
  YumeNailBarDb:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      container_name: sql_server2022
      ports: # not actually needed, because the two services are on the same network
        - "1433:1433"
      environment:
        - ACCEPT_EULA=y
        - SA_PASSWORD=TEST
  yumenailbar.webapi:
    image: yumenailbar.webapi
    ports:
      - 8001:80
    depends_on:
      - YumeNailBarDb
    build:
      context: .
      dockerfile: YumeNailBar.WebApi/Dockerfile
