networks:
  yumenailbarnetwork:

services:
  YumeNailBarDb:
      image: "postgres:16beta1-bullseye"
      container_name: PostgreSQL
      ports:
        - "5433:5432"
      environment:
        - POSTGRES_USER=flacko1703
        - POSTGRES_PASSWORD=Example96!
        - POSTGRES_DB=YumeNailBarDb
      networks:
        - yumenailbarnetwork
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
  yumenailbar.webapi:
    image: yumenailbar.webapi
    container_name: yumenailbarapi
    depends_on:
      - YumeNailBarDb
    build:
      context: .
      dockerfile: YumeNailBar.WebApi/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Zezenzus1703!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - yumenailbarnetwork
