# This is a generated file. Not intended for manual editing.
services:
  yumenailbar.webapi:
    build:
      context: "C:\\DEV\\YumeNailBar"
      dockerfile: "YumeNailBar.WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/YumeNailBar.WebApi.dll"
    environment: {}
    image: "yumenailbar.webapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\proto\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https"
    - "C:\\Users\\proto\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "C:\\DEV\\YumeNailBar\\YumeNailBar.WebApi:/app:rw"
    working_dir: "/app"
