# This is a generated file. Not intended for manual editing.
services:
  yumenailbar.webapi:
    build:
      context: "C:\\DEV\\YumeNailBar"
      dockerfile: "YumeNailBar.WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "yumenailbar.webapi:dev"
    ports:
    - "57000:57100"
    - "57200:57300"
    volumes:
    - "C:\\Users\\proto\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https"
    - "C:\\Users\\proto\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "C:\\DEV\\YumeNailBar\\YumeNailBar.WebApi:/app:rw"
    - "C:\\Users\\proto\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.1.2\\\
      Linux64:/riderDebugger"
    - "C:\\Users\\proto\\AppData\\Local\\JetBrains\\Toolbox\\apps\\Rider\\ch-0\\231.9011.39/bin:/riderLogsConf"
    - "C:\\Users\\proto\\AppData\\Local\\JetBrains\\Rider2023.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_5_29_12_41_06:/riderLogs:rw"
    working_dir: "/app"
