# This is a generated file. Not intended for manual editing.
services:
  yumenailbar.webapi:
    build:
      context: "C:\\DEV\\YumeNailBar"
      dockerfile: "YumeNailBar.WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "yumenailbar.webapi:dev"
    ports:
    - "57002:57100"
    - "57202:57300"
    volumes:
    - "C:\\DEV\\YumeNailBar\\YumeNailBar.WebApi:/app:rw"
    - "C:\\Users\\proto\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.1.1\\\
      Linux64:/riderDebugger"
    - "C:\\Users\\proto\\AppData\\Local\\JetBrains\\Toolbox\\apps\\Rider\\ch-0\\231.8770.54/bin:/riderLogsConf"
    - "C:\\Users\\proto\\AppData\\Local\\JetBrains\\Rider2023.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_5_18_00_11_32:/riderLogs:rw"
    working_dir: "/app"
