// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YumeNailBar.Infrastructure.Persistence.EF.Contexts.ApplicationContext;

#nullable disable

namespace YumeNailBar.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YumeNailBar.Domain.AggregateModels.RegistrationAggregate.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("YumeNailBar.Domain.AggregateModels.RegistrationAggregate.Entities.Procedure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("YumeNailBar.Domain.AggregateModels.RegistrationAggregate.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("YumeNailBar.Domain.AggregateModels.RegistrationAggregate.Entities.Procedure", b =>
                {
                    b.HasOne("YumeNailBar.Domain.AggregateModels.RegistrationAggregate.Registration", null)
                        .WithMany("Procedures")
                        .HasForeignKey("RegistrationId");
                });

            modelBuilder.Entity("YumeNailBar.Domain.AggregateModels.RegistrationAggregate.Registration", b =>
                {
                    b.Navigation("Procedures");
                });
#pragma warning restore 612, 618
        }
    }
}
