# fly.toml app configuration file generated for yumenailbar on 2023-05-27T08:02:53+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yumenailbar"
primary_region = "ams"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
