# fly.toml app configuration file generated for yumenailbarapi on 2023-06-02T00:32:51+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yumenailbarapi"
primary_region = "ams"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
